POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Keep it simple",
    "author": "Simple Man",
    "url": "www.simpleprogramming.com",
    "likes": 22
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Get rich quick",
    "author": "Napoleon Hill",
    "url": "www.ponziscamsfakewebsite.com",
    "likes": 15
}